### ISSUE TITLE
npcs/mobs and other players

### ISSUE THREAD

**Issue by ghost** [npetrovski/l2-world-map#1]
Hello first, congratulations on your work.
I follow your lineage projects, I find it very interesting.

I have some questions about the map

How do I add the npcs/mobs and other players on the map?

That's the way I'm doing it, but I can't display the npc on the map.

```
        const zoom = (slider.value * 10) / slider.max,
          rect = container.getBoundingClientRect(),
          halfWidth = rect.width / 2,
          halfHeight = rect.height / 2;

        const offsetX = WorldToPic(npcX, zoom),
          offsetY = WorldToPic(npcY, zoom);

          ctx.fillStyle = 'blue';
         ctx.fillRect(halfWidth - offsetX  , halfHeight - offsetY, 10, 10);
```

**Comment by npetrovski** [comment]
You can check out the latest version, or see the demo at https://npetrovski.github.io/l2-world-map/
